//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamhashoService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogViewer
    {
        public int Id { get; set; }
        public int BlogId { get; set; }
        public string Country { get; set; }
        public string Town { get; set; }
        public string IpAddress { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Blog Blog { get; set; }
    }
}
