//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamhashoService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long Id { get; set; }
        public Nullable<long> ProductId { get; set; }
        public string Message { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public byte NotificationTypeId { get; set; }
        public bool FromCustomer { get; set; }
        public bool IsRead { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
